import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { poppins } from '../ui/fonts';
import Footer from './websitedevelopment/components/footer';
import { Providers } from './provider';

export const metadata: Metadata = {
  title: 'XYZ Studio',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" sizes="any" />
      </head>
      <body className={`${poppins.className} antialiased`}>
        <>
          <Providers>{children}</Providers>
          <Footer />
        </>
      </body>
    </html>
  );
}
