import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { poppins } from '../ui/fonts';
import Footer from './websitedevelopment/components/footer';

export const metadata: Metadata = {
  title: 'Xyz Studio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <>
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
