import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Mobile Development XYZ Studio',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function MobileDevelopmentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
